// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8UGEEGQuM3uSsxY2KI0d5U0M0hxWGjyc',
    appId: '1:933253592657:web:4fdac9c6ce46f606666a70',
    messagingSenderId: '933253592657',
    projectId: 'unipaz-aa94c',
    authDomain: 'unipaz-aa94c.firebaseapp.com',
    storageBucket: 'unipaz-aa94c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAL83LT8rAkna8g62WZ2SDHYqJOG5CgsW0',
    appId: '1:933253592657:android:9fedb512dd30d9f9666a70',
    messagingSenderId: '933253592657',
    projectId: 'unipaz-aa94c',
    storageBucket: 'unipaz-aa94c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzf7jDxFEUFzjYZWJjHHc1CX-JUr3U-lY',
    appId: '1:933253592657:ios:5c78b4bbf3440d51666a70',
    messagingSenderId: '933253592657',
    projectId: 'unipaz-aa94c',
    storageBucket: 'unipaz-aa94c.appspot.com',
    iosClientId: '933253592657-fs85s57jc9pagierb2ha45sighd3cte7.apps.googleusercontent.com',
    iosBundleId: 'com.unipaz.unipaz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzf7jDxFEUFzjYZWJjHHc1CX-JUr3U-lY',
    appId: '1:933253592657:ios:6065631cbe354453666a70',
    messagingSenderId: '933253592657',
    projectId: 'unipaz-aa94c',
    storageBucket: 'unipaz-aa94c.appspot.com',
    iosClientId: '933253592657-nfmhfqt60qn5q3kaqs4bopuqefvur6i2.apps.googleusercontent.com',
    iosBundleId: 'com.unipaz.unipaz.RunnerTests',
  );
}
